### ISSUE TITLE
Copyright and license violation

### ISSUE THREAD

**Issue by mdyring** [xar-network/xar-network#6]
Dear @andrecronje,

It has come to our attention that your repository https://github.com/xar-network/xar-network contains code copied or derived from https://github.com/e-money/em-ledger:

The below list of modules have been copied or derived without permission and proper license:

https://github.com/xar-network/xar-network/tree/master/x/authority
copied from https://github.com/e-money/em-ledger/tree/master/x/authority

https://github.com/xar-network/xar-network/tree/master/x/interest
copied from https://github.com/e-money/em-ledger/tree/master/x/inflation

https://github.com/xar-network/xar-network/tree/master/x/issuer
copied from https://github.com/e-money/em-ledger/tree/master/x/issuer

https://github.com/xar-network/xar-network/tree/master/x/liquidityprovider
copied from https://github.com/e-money/em-ledger/tree/master/x/liquidityprovider

Per https://github.com/e-money/em-ledger/blob/master/LICENSE our source code is licensed as:
_This software is Copyright (c) 2019 e-Money A/S. It is not offered under an open source license. 
Please contact partners@e-money.com to for licensing related questions._

While we understand that you might have violated our licensing terms by mistake, please take **immediate action** to remove all modules and any other copied/derived artefacts from your repository and commit history, no later than December 6, 2019.

Thank you for your understanding,

Martin Dyring-Andersen
e-Money A/S

**Comment by andrecronje** [comment]
Reached out to all relevant parties & Martin when identified, busy actioning with team now. Will have resolved before December 6, thank you for raising.
